services:
  - type: web
    name: pdks-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: pdks-data
      mountPath: /opt/render/project/src/server/data
      sizeGB: 1
